version: '3.8'

services:
  app:
    image: microservicio-recomendador  # Cambia esto por tu imagen Docker para la app
    container_name: api-recomendacion2
    environment:
      - MYSQL_HOST=host.docker.internal  # Apunta a tu máquina local
      - MYSQL_PORT=3307                  # Puerto de MySQL local
      - MYSQL_USER=root
      - MYSQL_PASS=jhordan64
      - MYSQL_DB_NAME=tesisconnect
      - PORT=3000
      - JWT_SEED=semillaParaJWT
    ports:
      - "8000:8000"  # Puertos que expone la app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge