swagger: '2.0'
info: 
  version: '1.0.0'
  title: api-bonik
  description: This api login and register user
host: api-bonik.apigateway.probable-axon-424104-t6.cloud.goog # link base
# basepath: /apis/user # 
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/auth/login:
    post:
      description: post user login
      operationId: postLoginUser
      summary: loginuser
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      operationId: optionsLoginUser
      summary: CORS preflight
      responses:
        '204':
          description: No content
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
      x-google-extensions:
        - type: cors
          origin: ["*"]
          method: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          responseHeader: ["Content-Type"]
  /api/auth/register:
    post:
      description: Creates a new user
      operationId: postRegisterUser
      summary: registeruser
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      operationId: optionsRegisterUser
      summary: CORS preflight
      responses:
        '204':
          description: No content
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
      x-google-extensions:
        - type: cors
          origin: ["*"]
          method: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          responseHeader: ["Content-Type"]
  /api/seed/gradoAcademico:
    get:
      description: Crear grados academidos
      operationId: getSeedGradoAcademido
      summary: SeedGradoAcademido
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      operationId: optionsSeedGradoAcademido
      summary: CORS preflight
      responses:
        '204':
          description: No content
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
      x-google-extensions:
        - type: cors
          origin: ["*"]
          method: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          responseHeader: ["Content-Type"]
  /api/seed/especialidades:
    get:
      description: Crear grados academidos
      operationId: getSeedEspecialidades
      summary: SeedEspecialidades
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      operationId: optionsSeedEspecialidades
      summary: CORS preflight
      responses:
        '204':
          description: No content
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
      x-google-extensions:
        - type: cors
          origin: ["*"]
          method: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          responseHeader: ["Content-Type"]
  /api/seed/carreras:
    get:
      description: Crear grados carreras
      operationId: getSeedCarreras
      summary: SeedCarreras
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      operationId: optionsSeedCarreras
      summary: CORS preflight
      responses:
        '204':
          description: No content
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
      x-google-extensions:
        - type: cors
          origin: ["*"]
          method: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          responseHeader: ["Content-Type"]
  /api/general/especialidades:
    get:
      description: Obtener especialidades
      operationId: getEspecialidades
      summary: GetEspecialidades
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
  /api/general/gradosAcademicos:
    get:
      description: Obtener grados academicos
      operationId: getGradosAcademicos
      summary: GetGradosAcademicos
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
  /api/auth/informacion/{id}:
    get:
      description: Obtener usuario por id
      operationId: getUserById
      summary: GetUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      operationId: optionsUserbyId
      summary: CORS preflight
      responses:
        '204':
          description: No content
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-google-backend:
        address: https://api-usuario-609569711189.us-central1.run.app
      x-google-extensions:
        - type: cors
          origin: ["*"]
          method: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          responseHeader: ["Content-Type"]
  /recomendaciones/por-id-y-fecha:
    get:
      description: Obtener recomendaciones de usuario por id
      operationId: getRecomendacionesUserById
      summary: GetRecomendacionesUserById
      parameters:
        - name: id_investigador
          in: query
          required: true
          schema:
            type: string
      x-google-backend:
        address: https://api-recomendacion-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
  /recomendaciones/{id}:
    get:
      description: Generar y Obtener recomendaciones de usuario por id
      operationId: getGenerarRecomendacionesUserById
      summary: GetGenerarRecomendacionesUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      x-google-backend:
        address: https://api-recomendacion-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
  /recomendaciones:
    get:
      description: Generar todas las recomendaciones
      operationId: getGenerarAllRecomendaciones
      summary: GetGenerarAllRecomendaciones
      x-google-backend:
        address: https://api-recomendacion-609569711189.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-extensions:
        - type: cors
          method: "*"
          origin: ["*"]
          responseHeaders: ["Content-Type"]
      consumes:
      - application/json
      produces:
      - application/json
      deprecated: false
      responses:
        '200':
          description: A successful response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"