FROM python:3.11-slim

WORKDIR /app

COPY ./src ./src
COPY main.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

# Usa directamente python para que las variables se expandan correctamente
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]