# Usa una imagen oficial de Python
FROM python:3.11-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios
COPY ./src ./src
COPY requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto para FastAPI
EXPOSE 8080

# Comando para iniciar Uvicorn
CMD ["sh", "-c", "PYTHONPATH=./src uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8080}"]